[tests] add localstack env with TF dynamo module

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -12,6 +12,10 @@ vars:
   go_fumpt: latest
   go_lint: v2.1.2
 
+  terraform: 1.9.5
+
+  localstack_py_env: "{{.HOME}}/.pyenv_localstack"
+
   base_name: godyno
   bin_dir: "{{.git_root}}/bin/"
 
@@ -97,6 +101,46 @@ tasks:
     silent: true
     internal: true
 
+  _terraform/install:
+    desc: Install 'terraform'.
+    cmds:
+      - curl -sL https://releases.hashicorp.com/terraform/{{.terraform}}/terraform_{{.terraform}}_{{OS}}_{{ARCH}}.zip -o /tmp/terraform.zip
+      - sudo unzip -o /tmp/terraform.zip -d /usr/local/bin/
+      - sudo chmod a+x /usr/local/bin/terraform
+      - terraform version
+    sources:
+      - /usr/local/bin/terraform
+    silent: true
+    internal: true
+
+  _terraform/apply:
+    desc: Apply terraform to localstack
+    dir: "{{.DIR}}"
+    deps:
+      - _terraform/install
+    cmds:
+      - |
+        cat << EOF > backend.tf
+        terraform {
+          backend "local" {}
+        }
+        EOF
+
+        terraform init -reconfigure
+        terraform apply -input=false -auto-approve {{.TF_VARS}}
+    silent: true
+    internal: true
+
+  _localstack/install:
+    desc: Install "localstack".
+    cmds:
+      - python3 -m venv {{.localstack_py_env}}
+      - "{{.localstack_py_env}}/bin/python3 -m pip install localstack"
+    sources:
+      - "{{.localstack_py_env}}/bin/localstack"
+    silent: true
+    internal: true
+
   # =================================================
   # ----------------------PUBLIC--------------------#
   # =================================================
@@ -133,12 +177,29 @@ tasks:
       - "{{.go_root}}/bin/golangci-lint run"
     silent: true
 
+  localstack/run:
+    desc: Run localstack environment.
+    deps:
+      - _localstack/install
+    cmds:
+      - |
+        if [ -z "$LOCALSTACK_AUTH_TOKEN" ]; then
+          echo "Error: LOCALSTACK_AUTH_TOKEN is not set. Please set this environment variable before running LocalStack."
+          exit 1
+        fi
+      - "{{.localstack_py_env}}/bin/localstack start -d"
+      - task: _terraform/apply
+        vars:
+          DIR: "{{.git_root}}/tests/localstack/env"
+          TF_VARS: |
+            -var="use_localstack=true"
+
   # =================================================
   # -----------------------TEST---------------------#
   # =================================================
 
   go/tests/app:
-    desc: Tests app with basic cli checks 
+    desc: Tests app with basic cli checks.
     dir: "{{ .git_root }}/internal" 
     deps:
       - go/mod/vendor 
@@ -146,7 +207,7 @@ tasks:
     silent: true
 
   go/tests/template:
-    desc: Tests template parts statc
+    desc: Tests template parts statc.
     dir: "{{ .git_root }}/tests/parts" 
     deps:
       - go/mod/vendor 
@@ -154,7 +215,7 @@ tasks:
     silent: true
 
   go/tests/compile:
-    desc: Tests full template fromtatter, build, vet
+    desc: Tests full template fromtatter, build, vet.
     dir: "{{ .git_root }}/tests/validation" 
     deps:
       - go/mod/vendor 
@@ -163,7 +224,7 @@ tasks:
     silent: true
 
   go/tests/localstack:
-    desc: Func test generated template with localstack environment
+    desc: Func test generated template with localstack environment.
     dir: "{{ .git_root }}/tests/localstack"
     deps:
       - go/mod/vendor
@@ -172,7 +233,7 @@ tasks:
         echo "Hello"
   
   go/tests/all:
-    desc: Run all tests
+    desc: Run all tests.
     dir: "{{ .git_root }}"
     deps:
       - go/mod/vendor
@@ -186,7 +247,7 @@ tasks:
   # =================================================
 
   go/build/darwin_amd64:
-    desc: Build for macOS Intel (darwin/amd64)
+    desc: Build for macOS Intel (darwin/amd64).
     cmds:
       - task: _go/dyno/build
         vars:
@@ -194,7 +255,7 @@ tasks:
           GOARCH: amd64 
 
   go/build/darwin_arm64:
-    desc: Build for macOS Apple Silicon (darwin/arm64)
+    desc: Build for macOS Apple Silicon (darwin/arm64).
     cmds: 
       - task: _go/dyno/build
         vars: 
@@ -202,7 +263,7 @@ tasks:
           GOARCH: arm64 
   
   go/build/linux_amd64:
-    desc: Build for Linux x86_64 (linux/amd64)
+    desc: Build for Linux x86_64 (linux/amd64).
     cmds: 
       - task: _go/dyno/build
         vars:
@@ -210,7 +271,7 @@ tasks:
           GOARCH: amd64
 
   go/build/linux_386:
-    desc: Build for linux 32-bit (linux/386)
+    desc: Build for linux 32-bit (linux/386).
     cmds:
       - task: _go/dyno/build
         vars: 
@@ -218,7 +279,7 @@ tasks:
           GOARCH: "386"
 
   go/build/linux_arm:
-    desc: Build for Linux ARM 32-bit (linux/arm)
+    desc: Build for Linux ARM 32-bit (linux/arm).
     cmds:
       - task: _go/dyno/build
         vars: 
@@ -227,7 +288,7 @@ tasks:
           GOARM: "7"
 
   go/build/linux_arm64:
-    desc: Build for Linux ARM 6640bit (linux/arm64)
+    desc: Build for Linux ARM 6640bit (linux/arm64).
     cmds: 
       - task: _go/dyno/build
         vars:
